baseURL = "https://blog.pipetail.io"
title = "PipeTail Blog"
copyright = "Copyright Â© 2020 | TAIL. All rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
#DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "pipetail"
    name = "PipeTail"
    url = "https://pipetail.io"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Pipetail"
  description = "By Engineers. For Engineers."
  homepageImage = "images/title.jpg"
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = true
    email = "contact@pipetail.io"
    #facebook = "https://facebook.com"
    twitter = "https://twitter.com/pipetail.io"
    #linkedin = "https://linkedin.com"
    #stack-overflow = "https://stackoverflow.com"
    #instagram = "https://stackoverflow.com"
    github = "https://github.com/pipetail"
    #weibo = "https://www.weibo.com"
    #medium = "https://medium.com"
    #pinterest = "https://pinterest.com"
    #reddit = "https://reddit.com"
    #gitlab = "https://gitlab.com"
    #mastodon = "https://mastodon.social"
    #keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

